bind 127.0.0.1
port 6380
protected-mode yes
daemonize no
supervised no
dir /home/ubuntu/sunsq/phdebate-v2/runtime/redis
dbfilename dump.rdb
appendonly yes
appendfilename appendonly.aof
save 900 1
save 300 10
maxmemory 512mb
maxmemory-policy allkeys-lru

