[program:jixia-https-nginx]
priority=200
command=/usr/sbin/nginx -c /home/ubuntu/sunsq/phdebate/deploy/jixia-nginx-root.conf -g "daemon off;"
autostart=true
autorestart=true
startsecs=3
stopasgroup=true
killasgroup=true
stdout_logfile=/home/ubuntu/sunsq/phdebate/runtime/logs/nginx-supervisor.stdout.log
stderr_logfile=/home/ubuntu/sunsq/phdebate/runtime/logs/nginx-supervisor.stderr.log
stdout_logfile_maxbytes=20MB
stdout_logfile_backups=3
stderr_logfile_maxbytes=20MB
stderr_logfile_backups=3
