/home/ubuntu/sunsq/phdebate/runtime/logs/nginx-access.log
/home/ubuntu/sunsq/phdebate/runtime/logs/nginx-error.log {
    daily
    rotate 14
    maxsize 100M
    missingok
    notifempty
    compress
    delaycompress
    create 0640 root root
    sharedscripts
    postrotate
        test ! -s /run/nginx-jixia.pid || kill -USR1 "$(cat /run/nginx-jixia.pid)"
    endscript
}
